name: automia
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch=2.4.1
  - torchvision=0.19.1
  - pytorch-cuda=12.1
  - numpy=1.26.*
  - matplotlib=3.9.*
  - tqdm=4.66.*
  - pillow=10.4.*
  - opencv=4.10.*
  - trimesh=4.4.*
  - scikit-image=0.24.*
  - scipy=1.14.*
  - pip:
      - --find-links=https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py310_cu121_pyt241/download.html
      - pytorch3d==0.7.8
